version: '3.8'

networks:
  blog:
    driver: bridge

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb-composed
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    command: --pid-file=/var/run/mysqld/mysqld.pid
    networks:
      - blog

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    depends_on:
      - mysqldb
    networks:
      - blog

  frontend:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $WEBAPP_LOCAL_PORT:$WEBAPP_DOCKER_PORT
    networks:
      - blog




